language: ruby
sudo: false
rvm:
  - 2.5
  - 2.4
  - 2.3
  - jruby-9.1.9.0
gemfile:
  - gemfiles/ar51.gemfile
  - gemfiles/ar52.gemfile
  - gemfiles/ar60.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.1.9.0
  exclude:
  - rvm: 2.4
    gemfile: gemfiles/ar60.gemfile
  - rvm: 2.3
    gemfile: gemfiles/ar60.gemfile
services:
  - postgresql
addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
env:
  global:
    - PGUSER=travis
    - PGHOST=""
    - PGPORT=5433
before_script:
  - psql -U travis -c "create database postgis_adapter_test"
  - psql -U travis -d postgis_adapter_test -c "create extension postgis"
script: bundle exec rake test
before_install:
  - gem update --system
  - gem install bundler
